### PR TITLE
Cross platform build support and support for matching object files

### PR DESCRIPTION
**Pull request by TheOnlyZac**
This pull request does the following:
 - Refactors the code to use Boost for file IO rather than the Windows API, so it now compiles and runs on Linux.
 - Adds support for matching against a single precompiled object file with `--match`.
 - Tweaks the command line input and console output format.

### CODE REVIEW

**Comment by TheOnlyZac** [comment]
I have not tested this on Windows at all so that will need to be checked before this is ready to merge.

**Comment by felinis** [comment]
I appreciate the PR!
The code compiles but the `--compile` mode is broken.
I tested on your `sly1` repo:
```
$ CodeMatcher/build/CodeMatcher CodeMatcher/sly_proto.elf -c ~/sly1/src/P2
=== CodeMatcher 1.2 - Dec 6 2023 ===
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::directory_iterator::construct: No such file or directory [system:2]: "/home/me/sly1/src/P2/*.c"
Terminated (core dumped)
```
After closer inspection, I noticed that there are only `*.cpp` files in your `sly1` repo so I reflected that in code by changing line 53 of file `src/CCompiler.cpp` to `*.cpp`. I am getting the same error, though.
Moreover, I noticed that the path to the PS2 compiler still uses Windows path separators `\\` in file `src/CCompiler.cpp` and that will also cause issues in the future.

**Comment by TheOnlyZac** [comment]
I think that should be fixed now, but there is either something wrong with how I implemented `--match` mode or with how we're compiling the object files for the sly1 project. Some functions match I when compile and match the entire source tree with `--compile` in CodeMatcher, but nothing matches if I compile sly1 separately and then run `--match util.o`.

**Comment by TheOnlyZac** [comment]
I think it's the sly1 obj files, not CodeMatcher, because all the sizes it says the functions should be are consistent.

With `--compile` mode:
```
----------------------------------------------------------------
+ Comparing 'clock.c'
----------------------------------------------------------------
NOT MATCHING ---- 'SetClockRate(float)' (size 76, should be 72)
NOT MATCHING ---- 'MarkClockTick(CLOCK *)' (size 124, should be 320)
NOT MATCHING ---- 'MarkClockTickRealOnly(CLOCK *)' (size 68, should be 152)
MATCHING -------- 'ResetClock(CLOCK *, float)'
PLEASE DECOMP --- 'SetClockEnabled(CLOCK *, int)' at 0x148648
NOT MATCHING ---- 'StartupClock(void)' (size 36, should be 52)
NOT MATCHING ---- 'TickNow(void)' (size 8, should be 68)
```

With `--match` mode:
```
----------------------------------------------------------------
+ Comparing 'clock.c'
----------------------------------------------------------------
NOT MATCHING ---- 'SetClockRate(float)' (size 144, should be 72)
NOT MATCHING ---- 'MarkClockTick(CLOCK *)' (size 440, should be 320)
NOT MATCHING ---- 'MarkClockTickRealOnly(CLOCK *)' (size 208, should be 152)
NOT MATCHING ---- 'ResetClock(CLOCK *, float)' (size 68, should be 8)
PLEASE DECOMP --- 'SetClockEnabled(CLOCK *, int)' at 0x148648
NOT MATCHING ---- 'StartupClock(void)' (size 72, should be 52)
NOT MATCHING ---- 'TickNow(void)' (size 60, should be 68)
```

**Comment by TheOnlyZac** [comment]
Turns out I was actually just compiling the object files with -O0 instead of -O2, but if I change that it matches as expected.

**Comment by felinis** [comment]
Perfect. Thank you for the PR! I am glad that you resolved other issues as well.

**Pull request merged**
